export const rowData = {
  id: 'ID',
  number: 'Number',
  type: 'Type',
  rooms: 'Rooms',
  square: 'Square',
  building: 'Building',
  section: 'Section',
  floor: 'Floor',
  pricePerM: 'Price $/m2',
  priceTotal: 'Total price $',
  status: 'Status',
};

export const dataSection = [
  {
    id: '1',
    number: '1',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'sold',
  },
  {
    id: '2',
    number: '2',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'sold',
  },
  {
    id: '3',
    number: '3',
    type: 'zxvdz',
    rooms: '3',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '5000',
    priceTotal: '50000',
    status: 'reserved',
  },
  {
    id: '4',
    number: '4',
    type: 'ghf124',
    rooms: '2',
    square: '58',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '300',
    priceTotal: '5580',
    status: 'free',
  },
  {
    id: '5',
    number: '5',
    type: 'fd45hbvmc',
    rooms: '5',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'sold',
  },
  {
    id: '6',
    number: '6',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'sold',
  },
  {
    id: '7',
    number: '7',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'free',
  },
  {
    id: '8',
    number: '8',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'free',
  },
  {
    id: '9',
    number: '9',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'free',
  },
  {
    id: '10',
    number: '10',
    type: 'fsgfs',
    rooms: '2',
    square: '23',
    building: '1',
    section: '2',
    floor: '5',
    pricePerM: '2000',
    priceTotal: '20000',
    status: 'free',
  },
];

// export const rowData = [
//   id
//   number,
//   type,
//   rooms,
//   square,
//   building,
//   section,
//   floor,
//   pricePerM,
//   priceTotal,
//   status,
// ];
